apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-service
spec:
  replicas: {{ .Values.botService.replicas }}
  selector:
    matchLabels:
      app: bot-service
  template:
    metadata:
      labels:
        app: bot-service
    spec:
      containers:
      - name: bot-service
        image: {{ .Values.botService.image }}
        env:
        - name: AI_SERVICE_URL
          value: http://ai-service/analyze
